In [1]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4]),)


In [4]:
y=np.where(arr==7)
print(y)

(array([3]),)


In [5]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [6]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%3==1)
print(x)

(array([0, 3, 5]),)


In [10]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [11]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
x=np.sort(arr)
print(x)

[2 4 5 6 7 9]


In [18]:
arr=np.array([[7,4,9],[9,1,4]])
x=(np.sort(arr))
print(x)

[[4 7 9]
 [1 4 9]]


In [20]:
#BOOLEAN INDEXING
import numpy as np
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]


In [25]:
filter=arr>70
newarr=arr[filter]
print(filter)
print(newarr)

[False  True False  True]
[ 78 100]
