In [39]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
slice2=arr[::2]
slice3=arr[::3]
print(slice1)
print(slice2)
print(slice3)

[3 4 5 6]
[1 3 5 7 9]
[1 4 7]


In [10]:
reversedarray=arr[::-1]
print(reversedarray)

[9 8 7 6 5 4 3 2 1]


In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:2,1:3]
print("slicing:\n",substring)
col1=arr[:,0]
print("Column slicing :\n",col1)

slicing:
 [[2 3]
 [5 6]]
Column slicing :
 [1 4 7]


In [24]:
arr=np.array([[1,2,3,10],[4,5,6,20],[7,8,9,30]])
substring=arr[0:2,0:3:2]
print(substring)

[[1 3]
 [4 6]]


In [19]:
substring=arr[0:3:2,0:3:2]
print(substring)

[[1 3]
 [7 9]]


In [30]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:2,1:3]
print("slicing:\n",substring)
col1=arr[:,0]
print("Column slicing :\n",col1)

slicing:
 [[2 3]
 [5 6]]
Column slicing :
 [1 4 7]


In [32]:
row1=arr[0,:]
print("Row slicing:\n",row1)

Row slicing:
 [1 2 3]


In [35]:
print(arr[0:2:1])

[[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])

1


In [44]:
print(arr[2,1])

8


In [47]:
print(arr[1,2])

6


In [52]:
arr=[10,20,30,40,50,60]
print(arr[1])

20


In [53]:
print(arr[-1])

60


In [54]:
print(arr[1:4])

[20, 30, 40]


In [60]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[arr>25])

[30 40 50 60]


In [63]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[1:3])

[20 30]


In [5]:
#HORIZONTALJOINT
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
#VERTICALJOIN
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#DEPTHJOIN
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
