In [28]:
import numpy as np
a=np.array([1,2,3])
print("One Dimensional array : ",a)
print("\nNo of dimensions :",a.ndim)

One Dimensional array :  [1 2 3]

No of dimensions : 1


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Two Dimensional array : ",a)

Two Dimensional array :  [[1 2 3]
 [4 5 6]]


In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three Dimensional array : ",a)
print("\nNo of dimensions :",a.ndim)

Three Dimensional array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]

No of dimensions : 2


In [11]:
import numpy as np
a=np.zeros((3,5))
print("ZEROS MATRIX :",a)

ZEROS MATRIX : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
import numpy as np
a=np.random.random((3,5))
print("Random value: \n",a)

Random value: 
 [[0.44519656 0.44088845 0.03715937 0.60511578 0.10370066]
 [0.39513352 0.48434404 0.13831316 0.18555707 0.62768693]
 [0.39908599 0.64140616 0.29095872 0.33931064 0.7599975 ]]


In [15]:
import numpy as np
a=np.arange(8,29,3)
print("Sequence Matrix  : \n",a)

Sequence Matrix  : 
 [ 8 11 14 17 20 23 26]


In [25]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=a.reshape(4,3)
print("Original Array :\n",a)
print("\nReshaped Array :\n",newarr)

Original Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped Array :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat=arr.flatten()
print("Original array :\n",arr)
print("\nFlatten array :\n",flat)
print("\nNo of dimensions :",arr.ndim)

Original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flatten array :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

No of dimensions : 2


In [48]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\nNo of dimensions :",arr.ndim)
print("Shape of array :\n",arr.shape)
print("Length of array :",len(arr))


No of dimensions : 3
Shape of array :
 (2, 2, 3)
Length of array : 2


In [47]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Shape of array :",arr.shape)
print("Type of array : ",arr.dtype)
print("Length of array :",len(arr))

Shape of array : (3, 4)
Type of array :  int64
Length of array : 3


In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype )

[1. 2. 3.]
float64


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]
